### ISSUE TITLE
Improve logging during training

### ISSUE THREAD

**Issue by levmckinney** [AlignmentResearch/tuned-lens#86]
Currently, each distributed process just logs to standard out, and it is difficult to tell which process is producing which logs. I propose that we switch to using pythons built in logging utility and add a prefix to each process's logger which includes its process rank. So instead of printing something like:
```
Process finished setting up.
Process finished setting up.
Process finished setting up.
Process finished setting up.
Begining training loop.
Begining training loop.
...
```
What we want is something like this:
```
DEBUG (rank 0): Process finished setting up.
DEBUG (rank 1): Process finished setting up.
DEBUG (rank 2): Process finished setting up.
DEBUG (rank 3): Process finished setting up.
DEBUG (rank 1): Begining training loop.
DEBUG (rank 0): Begining training loop.
...
```

An alternative solution is to simply drop all messages except from the primary process using contextlib. While this is a bit simpler it provides less information for debugging and encourages the use of print statements.

**Comment by norabelrose** [comment]
Note that any solution to this problem will have to deal with the fact that some of the print statements are not even controlled by us; they're controlled by HuggingFace. That's why I originally used `contextlib.redirect_stdout` in an earlier version of this library and why I use it to suppress `bitsandbytes` welcome messages on ranks other than rank 0 in EleutherAI/elk.

I'm pro adding a prefix but it may end up being a little tricky since you'll probably have to like, parse the stdout into separate lines in order to find where to put the prefix.
<img width="1066" alt="Captura de pantalla 2023-05-01 a la(s) 9 53 39 a m" src="https://user-images.githubusercontent.com/39116809/235491774-79f9a02f-c8b4-48b1-9d1d-a9c7f48c7fe1.png">

**Comment by norabelrose** [comment]
HF does use `logging` for some of their stuff but other parts use `warnings` or whatever. And `bitsandbytes` annoyingly just uses a raw print statement.
